Global:
  debug: false
  use_gpu: true
  epoch_num: &epoch_num 2000
  log_smooth_window: 20
  print_batch_step: 100
  save_model_dir: ./output/rec_SVTR-LCNet_PPLCNetV3_first_50000
  save_epoch_step: 100
  eval_batch_step:
  - 0
  - 1000
  cal_metric_during_train: true
  # checkpoints: ./output/rec_SVTR-LCNet_PPLCNetV3_first_50000/latest
  pretrained_model: pretrain/en_PP-OCRv4_rec_train/best_accuracy
  save_inference_dir: ./output/rec_SVTR-LCNet_PPLCNetV3_first_50000
  use_visualdl: true
  infer_img: /data/parcel/annotations/rec/finetune/phase_3_images_all/phase_3_data/2023_10_15/20231015-CX844-1/2023-10-15T18-32-05_0000001562_camera09_17_gr_315066480272623369_daaaefdc-a748-4521-9725-1363137b1c78_f2cfae1c-df0e-4461-904c-05f281469273.jpg
  character_dict_path: ppocr/utils/en_dict.txt
  max_text_length: &max_text_length 25
  infer_mode: false
  use_space_char: true
  save_res_path: ./checkpoints/rec/predicts.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0005
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05


Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform:
  Backbone:
    name: PPLCNetV3
    scale: 0.95
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 120
            depth: 2
            hidden_dims: 120
            kernel_size: [1, 3]
            use_guide: True
          Head:
            fc_decay: 0.00001
      - NRTRHead:
          nrtr_dim: 384
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - NRTRLoss:

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: false
Train:
  dataset:
    name: MultiScaleDataSet
    ds_width: false
    data_dir: /data/parcel/annotations/
    ext_op_transform_idx: 1
    label_file_list:
      - /data/parcel/annotations/rec/finetune/first_50000_images_train_labels.txt
      - /data/parcel/annotations/rec/general/mjsynth_train_labels.txt
    ratio_list: [1.0, 0.002]
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [48, 320, 3]
        max_text_length: *max_text_length
    - RecAug:
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  sampler:
    name: MultiScaleSampler
    scales: [[320, 32], [320, 48], [320, 64]]
    first_bs: &bs 128
    fix_bs: false
    divided_factor: [8, 16] # w, h
    is_training: True
  loader:
    shuffle: true
    batch_size_per_card: *bs
    drop_last: true
    num_workers: 8
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /data/parcel/annotations/
    label_file_list:
      - /data/parcel/annotations/rec/finetune/first_50000_images_test_labels.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 4
